### PR TITLE
Function to plot motifs and inspect them visually

### PR DESCRIPTION
**Pull request by TheArrayOfSunshine**
1. I tried going through the existing functions in the package but could not find anything for this. 
2. This function can be used in an even better way if included directly in the find_motif function with a parameter of find_motif function being plot_motifs =TRUE/FALSE. 
3. This is the initial commit, will make further changes to include it into find_motif directly.
4. Function is thoroughly checked under multiple datasets.

### CODE REVIEW

**Comment by TheArrayOfSunshine** [comment]
One of the checks have failed. 
Any idea as why this happened? Changes and suggestions would be really appreciated.

**Comment by franzbischoff** [comment]
Hi, let me get thru this request with time. I'll reply ASAP.

**Comment by TheArrayOfSunshine** [comment]
No problem. I'll keep making changes and commits frequently in that while to the package and the documentation/comments. I hope that helps as I could see you are the only contributor to this package.

**Comment by franzbischoff** [comment]
Reviewing your suggestion, have you tried to use `plot()`?

```
w <- 50
data <- mp_gait_data
mp <- tsmp(data, window_size = w, exclusion_zone = 1/4, verbose = 0)
mp <- find_motif(mp)
plot(mp)
```

**Comment by franzbischoff** [comment]
Closed by lack of feedback

**Pull request closed without merging**
