### PR TITLE
Including Khiva and its bindings as other projects

### PR DESCRIPTION
**Pull request by otorreno**
Khiva is prepared for GPU and CPU execution. It has different bindings available (R, Matlab, Java, Python, Kotlin).

It could be interesting to check if GPU Stomp can be the STOMP implementation available in Khiva-R

### CODE REVIEW

**Comment by franzbischoff** [comment]
Err, now I got the pull request. This is only an addition to references right?
There is a matrix profile implementation in Khiva?
Cheers.

**Comment by franzbischoff** [comment]
As is says:

> #' STOMP algorithm to calculate the matrix profile between 'first.time.series' and 'second.time.series' using a subsequence length

So indeed it implements STOMP (Matrix Profile).
I'll merge your pull request as reference for MP projects.

**Comment by otorreno** [comment]
Sorry, I was in the middle of something and I didn't see your comments. Yes, we have the stomp implementation. Thanks for including the links. What should we do to include it in https://franzbischoff.github.io/tsmp/ as well?

**Comment by franzbischoff** [comment]
I would appreciate :-)

**Comment by otorreno** [comment]
I have just opened the PR #37 to regenerate the web with the khiva links

**Pull request merged**
